"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 01:25:51.164635
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import frameforge_server.db.types


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('paths', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('exclude_patterns', sa.JSON(), nullable=False),
    sa.Column('output_policy', sa.String(length=32), nullable=False),
    sa.Column('output_path', sa.String(length=1024), nullable=True),
    sa.Column('backup_path', sa.String(length=1024), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_scan_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_scan_summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hint', sa.String(length=16), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('reserve_slot_for_normal', sa.Boolean(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('path_mappings', sa.JSON(), nullable=False),
    sa.Column('hardware_hint', sa.String(length=16), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('last_metrics', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_token_hash'), ['token_hash'], unique=False)

    op.create_table('processed_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_fingerprints_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('builtin_key', sa.String(length=64), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), nullable=False),
    sa.Column('encode_seconds', sa.Float(), nullable=False),
    sa.Column('media_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', name='uq_stats_daily_day')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_login_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('relative_path', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('probe_error', sa.Text(), nullable=True),
    sa.Column('discovered_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('original_size', sa.BigInteger(), nullable=True),
    sa.Column('processed_profile_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_job_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_library_id'), ['library_id'], unique=False)
        batch_op.create_index('ix_media_files_library_status', ['library_id', 'status'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('skip_if_target_codec', sa.Boolean(), nullable=False),
    sa.Column('policy_group', sa.String(length=64), nullable=True),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_library_id'), ['library_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.String(length=2048), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('profile_spec', sa.JSON(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=128), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('waiting_reason', sa.String(length=255), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('node_name', sa.String(length=64), nullable=True),
    sa.Column('excluded_nodes', sa.JSON(), nullable=False),
    sa.Column('encoder', sa.String(length=32), nullable=True),
    sa.Column('backend', sa.String(length=16), nullable=True),
    sa.Column('hw_decode', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('source_codec', sa.String(length=32), nullable=True),
    sa.Column('target_codec', sa.String(length=32), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('source_duration', sa.Float(), nullable=True),
    sa.Column('source_size', sa.BigInteger(), nullable=True),
    sa.Column('output_size', sa.BigInteger(), nullable=True),
    sa.Column('output_path', sa.String(length=2048), nullable=True),
    sa.Column('finalize_plan', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('eta_seconds', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('diagnosis', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('assigned_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.Column('started_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)
        batch_op.create_index('ix_jobs_state_priority', ['state', 'priority'], unique=False)

    op.create_table('media_metadata',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('container', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('bitrate', sa.BigInteger(), nullable=True),
    sa.Column('video_codec', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('short_side', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('hdr_format', sa.String(length=32), nullable=True),
    sa.Column('audio_codecs', sa.JSON(), nullable=False),
    sa.Column('audio_count', sa.Integer(), nullable=False),
    sa.Column('subtitle_count', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('creation_time', frameforge_server.db.types.UTCDateTime(), nullable=True),
    sa.Column('frameforge_tag', sa.String(length=128), nullable=True),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.Column('probed_at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    with op.batch_alter_table('media_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_metadata_video_codec'), ['video_codec'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('at', frameforge_server.db.types.UTCDateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('media_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_metadata_video_codec'))

    op.drop_table('media_metadata')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_state_priority')
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_node_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_file_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_library_id'))

    op.drop_table('rules')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('ix_media_files_library_status')
        batch_op.drop_index(batch_op.f('ix_media_files_library_id'))
        batch_op.drop_index(batch_op.f('ix_media_files_fingerprint'))

    op.drop_table('media_files')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('stats_daily')
    op.drop_table('profiles')
    with op.batch_alter_table('processed_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_fingerprints_fingerprint'))

    op.drop_table('processed_fingerprints')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_token_hash'))

    op.drop_table('nodes')
    op.drop_table('libraries')
    # ### end Alembic commands ###
